apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # Leitura e Escrita uma vez
  hostPath: # tipo de disco
    path: "/tmp/data"