apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-dp
  labels:
    testapp: "yes"
spec:
  replicas: 2
  selector:
    matchLabels:
      testapp: "yes"
  template:
    metadata:
      labels:
        testapp: "yes"
    spec:
      containers:
      - name: milkshake
        image: https://github.com/FofuxoSibov/sitebike
        envFrom:
        - configMapRef:
            name: first-cfg
        - secretRef:
            name: first-sec