apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: teste4
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::998247749828:role/LabRole

vpc:
  id: vpc-072e93afc0633a909
  cidr: 172.31.0.0/16
  subnets:
    public:
      us-east-1a:
        id: subnet-0e1f261077aa92c5b
      us-east-1b:
        id: subnet-09e583ded94d1f4dc

nodeGroups:
  - name: ndg-2
    instanceType: t2.micro
    desiredCapacity: 1
    iam:
      instanceRoleARN: arn:aws:iam::998247749828:instance-profile/LabInstanceProfile
    privateNetworking: false
